# Generated by Django 2.0.7 on 2018-08-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0002_auto_20180805_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_a', models.ImageField(upload_to='banner/', verbose_name='首页广告1')),
                ('banner_b', models.ImageField(upload_to='banner/', verbose_name='首页广告2')),
                ('banner_c', models.ImageField(upload_to='banner/', verbose_name='首页广告3')),
                ('banner_d', models.ImageField(upload_to='banner/', verbose_name='首页广告4')),
                ('banner_e', models.ImageField(upload_to='banner/', verbose_name='首页广告5')),
                ('banner_a_xiao', models.ImageField(upload_to='banner/xiao/', verbose_name='首页广告1小图')),
                ('banner_b_xiao', models.ImageField(upload_to='banner/xiao/', verbose_name='首页广告2小图')),
                ('banner_c_xiao', models.ImageField(upload_to='banner/xiao/', verbose_name='首页广告3小图')),
                ('banner_d_xiao', models.ImageField(upload_to='banner/xiao/', verbose_name='首页广告4小图')),
                ('banner_e_xiao', models.ImageField(upload_to='banner/xiao/', verbose_name='首页广告5小图')),
                ('bannertext', models.CharField(max_length=120, verbose_name='banner文字')),
                ('bannerdetail', models.CharField(max_length=120, verbose_name='小字')),
                ('isdelete', models.BooleanField(default=False, verbose_name='是否可删除')),
            ],
        ),
    ]
