# Generated by Django 2.0.5 on 2018-08-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0003_indexbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexFootImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footimg_a', models.ImageField(upload_to='footimg/', verbose_name='底部图片1')),
                ('footimg_b', models.ImageField(upload_to='footimg/', verbose_name='底部图片2')),
                ('footimg_c', models.ImageField(upload_to='footimg/', verbose_name='底部图片3')),
                ('footimg_d', models.ImageField(upload_to='footimg/', verbose_name='底部图片4')),
                ('footimg_e', models.ImageField(upload_to='footimg/', verbose_name='底部图片5')),
                ('footimg_a_xiao', models.ImageField(upload_to='footimg/xiao/', verbose_name='底部广告1小图')),
                ('footimg_b_xiao', models.ImageField(upload_to='footimg/xiao/', verbose_name='底部广告2小图')),
                ('footimg_c_xiao', models.ImageField(upload_to='footimg/xiao/', verbose_name='底部广告3小图')),
                ('footimg_d_xiao', models.ImageField(upload_to='footimg/xiao/', verbose_name='底部广告4小图')),
                ('footimg_e_xiao', models.ImageField(upload_to='footimg/xiao/', verbose_name='底部广告4小图')),
            ],
            options={
                'verbose_name_plural': '底部广告图',
            },
        ),
        migrations.AlterModelOptions(
            name='indexbanner',
            options={'verbose_name_plural': '首页广告'},
        ),
    ]
