# Generated by Django 2.0.7 on 2018-08-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0003_indexbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120)),
                ('username', models.CharField(default='None', max_length=120)),
                ('kind_choices', models.CharField(choices=[('python', 'python'), ('php', 'php'), ('java', 'java'), ('c#', 'c#')], default=('python', 'python'), max_length=120)),
            ],
            options={
                'verbose_name_plural': '用户表单',
            },
        ),
        migrations.AlterModelOptions(
            name='indexbanner',
            options={'verbose_name_plural': '首页广告'},
        ),
    ]
