# Generated by Django 2.0.5 on 2018-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0004_auto_20180806_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120, verbose_name='提交内容')),
                ('username', models.CharField(max_length=120, verbose_name='提交用户')),
                ('kind_choices', models.CharField(choices=[('java', 'java'), ('php', 'php'), ('python', 'pyhon'), ('c++', 'c++')], default=('java', 'java'), max_length=120)),
            ],
            options={
                'verbose_name_plural': '用户提交信息',
            },
        ),
    ]
