# Generated by Django 2.0.5 on 2018-08-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0005_userkind'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaId', models.IntegerField(verbose_name='地区Id')),
                ('areaCode', models.CharField(max_length=20, verbose_name='地区编码')),
                ('areaName', models.CharField(max_length=120, verbose_name='地区名')),
                ('level', models.IntegerField(verbose_name='地区级别')),
                ('cityCode', models.CharField(max_length=20, verbose_name='城市编码')),
                ('center', models.CharField(max_length=20, verbose_name='城市中心点')),
                ('parentId', models.IntegerField(verbose_name='地区父节点')),
            ],
            options={
                'verbose_name_plural': '城市表',
            },
        ),
    ]
